# SPDX-License-Identifier: BUSL-1.1

version: '3.7'

services:
  freezer_clickhouse:
    image: clickhouse/clickhouse-server:latest
    pull_policy: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"
      - "8123:8123"
