# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
coin-distribution:
  alert-slack-webhook: https://hooks.slack.com/services/dummy/dummy/dummy
  environment: local
  review-url: https://some.bogus.example.com/going/somewhere
  startHours: 12
  endHours: 17
  development: true
  workers: 10
  batchSize: 100
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5433/freezer
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5433/freezer